import { faker } from '@faker-js/faker';

/**
 * South African data grouped for better structure and access
 */
export const SouthAfricaData = {
  mobilePrefixes: [
    '060',
    '076',
    '082',
    '061',
    '062',
    '078',
    '079',
    '083',
    '064',
    '065',
    '084',
    '081',
    '067',
    '063',
    '066',
    '068',
    '069',
    '071',
    '072',
    '073',
    '074',
    '087',
  ],

  address: {
    streets: [
      'Mandela',
      'Vilakazi',
      'Rivonia',
      'Voortrekker',
      'Church',
      'Long',
      'Main',
      'Oxford',
      'Jan Smuts',
      'Beyers Naude',
      'William Nicol',
      'Barry Hertzog',
      'Louis Botha',
      'Pritchard',
      'Commissioner',
      'Joubert',
      'Jeppe',
      'Marshall',
      'Anderson',
      'Grayston',
      'Katherine',
      'Republic',
      'Hendrik Verwoerd',
      'Eloff',
      'Simmonds',
    ],

    suburbs: [
      'Sandton',
      'Rosebank',
      'Parktown',
      'Houghton',
      'Melville',
      'Greenside',
      'Parkhurst',
      'Sea Point',
      'Camps Bay',
      'Claremont',
      'Newlands',
      'Observatory',
      'Woodstock',
      'Morningside',
      'Berea',
      'Umhlanga',
      'Westville',
      'Kloof',
      'Pinetown',
      'Hatfield',
      'Menlo Park',
      'Brooklyn',
      'Waterkloof',
      'Centurion',
      'Midrand',
      'Stellenbosch',
      'Paarl',
      'Somerset West',
      'Brackenfell',
      'Bellville',
    ],

    cities: [
      'Johannesburg',
      'Cape Town',
      'Durban',
      'Pretoria',
      'Port Elizabeth',
      'Bloemfontein',
      'East London',
      'Pietermaritzburg',
      'Nelspruit',
      'Polokwane',
      'Kimberley',
      'Rustenburg',
      'George',
      'Witbank',
      'Vanderbijlpark',
      'Springs',
      'Roodepoort',
    ],

    provinces: [
      'Gauteng',
      'Western Cape',
      'KwaZulu-Natal',
      'Eastern Cape',
      'Free State',
      'Limpopo',
      'North West',
      'Mpumalanga',
      'Northern Cape',
    ],

    streetTypes: ['Street', 'Road', 'Avenue', 'Drive', 'Lane', 'Way', 'Close'],

    postalCodeRanges: {
      Johannesburg: (): number =>
        faker.helpers.arrayElement([
          faker.number.int({ min: 1682, max: 1687 }), // Midrand
          faker.number.int({ min: 1801, max: 1868 }), // Soweto
          faker.number.int({ min: 2000, max: 2199 }), // Central + Northern suburbs
        ]) as number,

      'Cape Town': (): number => faker.number.int({ min: 7400, max: 8099 }) as number,
      Durban: (): number => faker.number.int({ min: 4000, max: 4099 }) as number,
      Pretoria: (): number => faker.number.int({ min: 1, max: 186 }) as number,
      Polokwane: (): number => faker.number.int({ min: 699, max: 787 }) as number,
      Bloemfontein: (): number => faker.number.int({ min: 9300, max: 9330 }) as number,
      'East London': (): number => faker.number.int({ min: 5200, max: 5299 }) as number,
      'Port Elizabeth': (): number => faker.number.int({ min: 6000, max: 6099 }) as number,
      Nelspruit: (): number => faker.number.int({ min: 1200, max: 1299 }) as number,
      Kimberley: (): number => faker.number.int({ min: 8300, max: 8399 }) as number,
      Rustenburg: (): number => faker.number.int({ min: 299, max: 301 }) as number,
      George: (): number => faker.number.int({ min: 6529, max: 6531 }) as number,
      default: (): number => faker.number.int({ min: 1000, max: 9999 }) as number,
    },
  },

  business: {
    streets: [
      'Rivonia',
      'Sandton',
      'Grayston',
      'West',
      'Katherine',
      'Republic',
      'Long',
      'Strand',
      'Loop',
      'Adderley',
      'St Georges Mall',
    ],

    areas: [
      'Sandton CBD',
      'Cape Town CBD',
      'Durban CBD',
      'Rosebank',
      'Parktown',
      'Century City',
      'Tyger Valley',
      'Gateway',
      'Nelson Mandela Bay',
    ],
  },
};
